### ISSUE TITLE
插件外部传值问题

### ISSUE THREAD

**Issue by lgbwust** [VoidAndNullity/MyTestProject#1]
https://github.com/VoidAndNullity/MyTestProject/blob/master/onlyoffice-plugin/main.js
您好，我用的onlyOffice是7.x版本，貌似失效了。请问下传值还有其它的解决方案吗？

**Comment by DreamNomad** [comment]
onlyoffice使用iframe嵌入的，只要解决一个跨域的问题也可以用iframe间通信进行传值。比如你的web应用和onlyoffice使用nginx进行反向代理，这样就能保证你的web和onlyoffice是同源的，也就能通信了，但这个方法我没尝试过。还有另外一种方式就是搭一个中间服务，比如插件内通过websocket和这个中间服务连接好，只要这个中间服务收到消息，就往插件推送，这个我也没尝试过，感觉行得通的解决思路，如果当中某个思路走通了或者有其他思路，可以分享下经验哈。
